### ISSUE TITLE
Error when changing numbers in code

### ISSUE THREAD

**Issue by AnkiDan** [ijgnd/anki__Extended_quick_reschedule_in_reviewer#1]
Loved the previous version of the add on, but for some reason whenever I try to change the days from 7, 30, and 365 to any other numbers, it says there is an error and wont let me use the app. Any advice on how to fix this? Using a MacOS 10.12.

**Comment by ijgnd** [comment]
Thanks for your report.

When I tried to reproduce the error I fixed another bug with negative values. Maybe this was your error. With the latest version I don't get any error messages in MacOS 10.11

- If you are not on Anki version 2.1.9 update and try again.
- Update your add-ons to get the latest version of this add-on.
- What is the error message you get?
- Do you have the add-on Rememorized installed?
- Did you reset your config? If you did and it still doesn't work maybe there is some error in your text. You could delete everything that is in the config window and replace it with the config from the blue box below. Does this help?


```json
{
    "access_dialog_from_reviewer": "g",
    "add_entry_to_context_menu": true,
    "add_num_area_to_dialog": false,
    "add_quick_buttons_to_dialog": true,
    "focus_lineedit": "r",
    "one_less_day": "d",
    "one_more_day": "f",
    "quick_buttons": [
        {
            "ivl": 10,
            "key": "t",
            "label": "about 10 days"
        },
        {
            "ivl": 45,
            "key": "g",
            "label": "about 45 days"
        },
        {
            "ivl": 730,
            "key": "b",
            "label": "two years"
        }
    ],
    "relearn_key": "a",
    "secondary_accept_1": "e",
    "secondary_accept_2": "space",
    "show_tooltip": true
}
```

**Comment by AnkiDan** [comment]
![image](https://user-images.githubusercontent.com/47947618/53306467-0511bb80-3853-11e9-922d-167f0098818c.png)
 So this is the error message I get. I'm not currently using Anki 2.1 since I prefer 2.0, but the previous version of your add on worked with 2.0 so not sure if that'd be the problem.

**Comment by ijgnd** [comment]
The json file that comes with the add-on works for me with Anki 2.0.52.

- Could you post the contents your config.json? Make sure that it is shown properly by putting three backticks \`\`\` in a new line before and after the contents to tell github that this is code?
- What happens if you replace the contents of your config.json with the text in the blue box from my last post?

**Comment by ijgnd** [comment]
You should also delete the old add-on "Extended Quick Reschedule in Reviewer".

**Comment by AnkiDan** [comment]
Finally got it to work, would only accept my edits if I typed between yours (for example, I typed "16 days" between the words "two" and "years", and then deleted those words. It would give me that error if I tried to delete those words then type my own. No clue why, but it's working now. Thanks for the help!

**Comment by ijgnd** [comment]
I'm glad it works. Then either you or your software adds or deletes characters so that it does no longer fulfil the json standard.  When you edit a json file make sure to use a text editor and don't use word processing software.

You could try a "json validator". If I google for "verify json online" my first hit is https://jsonlint.com/ . You could copy and paste the contents of your json file into such a service so that you see where you have errors in your file.

in general: json is a strict format and minor deviations cause errors. I listed some common errors in the error message that you saw.

**Comment by AnkiDan** [comment]
One more problem, this add on seems to prevent my other add on "Right hand reviews with jkl" from working, because whenever I delete the alternative dialog add on the right hand reviews start to work again. Any idea why that might be?

**Comment by ijgnd** [comment]
See #2
